[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  timeout = 30

[[redirects]]
  from = "/api/threads"
  to = "/.netlify/functions/threads"
  status = 200

[[redirects]]
  from = "/api/threads/:threadId/messages"
  to = "/.netlify/functions/add-message"
  status = 200

[[redirects]]
  from = "/api/threads/:threadId/runs"
  to = "/.netlify/functions/run-assistant"
  status = 200

[[redirects]]
  from = "/api/threads/:threadId/runs/:runId"
  to = "/.netlify/functions/run-status"
  status = 200

[[redirects]]
  from = "/api/threads/:threadId/runs/:runId/submit_tool_outputs"
  to = "/.netlify/functions/submit-tool-outputs"
  status = 200

[[redirects]]
  from = "/api/threads/:threadId/messages"
  to = "/.netlify/functions/messages"
  status = 200

[[redirects]]
  from = "/api/generate-career-image"
  to = "/.netlify/functions/generate-career-image"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200